[project]
name = "congmiao-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.14",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "mcp[cli]>=1.12.2",
]
